---
title: Can't Remember This Stuff

exclude: ['/scripts', '/Gemfile', '/Makefile', '/README.md']

permalink: pretty

collections:
  cantrememberthisstuff:
    output: true

defaults:
  - scope:
      path: '_cantrememberthisstuff'
    values:
      layout: bin
